[package]
authors = ["matthme"]
edition = "2021"
name = "moss_helpers"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "moss_helpers"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
