[package]
authors = ["eric@harris-braun.com"]
edition = "2021"
name = "peer_status_coordinator"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "peer_status_coordinator"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
