[package]
name = "assets"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "assets"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
assets_integrity = { workspace = true }
itertools = "0.13.0"
