[package]
edition = "2021"
name = "foyer"
version = "0.0.2"

[lib]
crate-type = ["cdylib", "rlib"]
name = "foyer"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
moss_helpers = { workspace = true }
foyer_integrity = { path = '../../integrity/foyer' }
