import { describe, expect, it } from 'vitest';

import {
  ASR_CATALOG_MODELS,
  parseLfsPointer,
  pointerUrl,
  renderCatalogData,
  type CatalogRow,
} from './asr-catalog-lib.mjs';

const POINTER = [
  'version https://git-lfs.github.com/spec/v1',
  'oid sha256:be07e048e1e599ad46341c8d2a135645097a538221678b7acdd1b1919c6e1b21',
  'size 77691713',
  '',
].join('\n');

describe('parseLfsPointer', () => {
  it('reads the sha256 and size from a HuggingFace LFS pointer', () => {
    expect(parseLfsPointer(POINTER)).toEqual({
      sha256: 'be07e048e1e599ad46341c8d2a135645097a538221678b7acdd1b1919c6e1b21',
      sizeBytes: 77_691_713,
    });
  });

  it('rejects text that is not a pointer, such as the binary itself or an HTML error page', () => {
    expect(() => parseLfsPointer('<html>not found</html>')).toThrow(/not an LFS pointer/);
    expect(() => parseLfsPointer('oid sha256:abc\nsize 10\n')).toThrow(/not an LFS pointer/);
  });
});

describe('ASR_CATALOG_MODELS', () => {
  it('lists unique ids with a latency tier each', () => {
    const ids = ASR_CATALOG_MODELS.map((m) => m.id);
    expect(new Set(ids).size).toBe(ids.length);
    expect(ids).toContain('base.en');
    for (const m of ASR_CATALOG_MODELS) expect(['fast', 'ok', 'slow']).toContain(m.latencyTier);
  });
});

describe('pointerUrl', () => {
  it('points at the raw pointer file, not the resolved binary', () => {
    expect(pointerUrl('base.en')).toBe(
      'https://huggingface.co/ggerganov/whisper.cpp/raw/main/ggml-base.en.bin',
    );
  });
});

describe('renderCatalogData', () => {
  const rows: CatalogRow[] = [
    { id: 'tiny', latencyTier: 'fast', sha256: 'a'.repeat(64), sizeBytes: 77_691_713 },
    { id: 'large-v3', latencyTier: 'slow', sha256: 'b'.repeat(64), sizeBytes: 3_095_033_483 },
  ];

  it('emits a generated TypeScript module with one row per model, in order', () => {
    const src = renderCatalogData(rows);
    expect(src).toMatch(/^\/\/ Generated by scripts\/update-asr-catalog\.mjs/);
    expect(src).toContain('export const ASR_MODEL_CATALOG_DATA');
    expect(src.indexOf("id: 'tiny'")).toBeLessThan(src.indexOf("id: 'large-v3'"));
    expect(src).toContain(`sha256: '${'a'.repeat(64)}'`);
    expect(src).toContain('sizeBytes: 3_095_033_483');
    expect(src.endsWith('\n')).toBe(true);
  });

  it('is deterministic, so --check can compare it byte for byte', () => {
    expect(renderCatalogData(rows)).toBe(renderCatalogData(rows));
  });
});
