// Generated by scripts/update-asr-catalog.mjs from the HuggingFace LFS
// pointers of ggerganov/whisper.cpp. Do not edit by hand: change
// ASR_CATALOG_MODELS in scripts/asr-catalog-lib.mjs and run
// `yarn update:asr-catalog`.

import type { AsrLatencyTier } from '@theweave/moss-types';

export interface AsrModelCatalogRow {
  id: string;
  latencyTier: AsrLatencyTier;
  sha256: string;
  sizeBytes: number;
}

export const ASR_MODEL_CATALOG_DATA: readonly AsrModelCatalogRow[] = Object.freeze([
  {
    id: 'tiny',
    latencyTier: 'fast',
    sha256: 'be07e048e1e599ad46341c8d2a135645097a538221678b7acdd1b1919c6e1b21',
    sizeBytes: 77_691_713,
  },
  {
    id: 'tiny.en',
    latencyTier: 'fast',
    sha256: '921e4cf8686fdd993dcd081a5da5b6c365bfde1162e72b08d75ac75289920b1f',
    sizeBytes: 77_704_715,
  },
  {
    id: 'base',
    latencyTier: 'ok',
    sha256: '60ed5bc3dd14eea856493d334349b405782ddcaf0028d4b5df4088345fba2efe',
    sizeBytes: 147_951_465,
  },
  {
    id: 'base.en',
    latencyTier: 'ok',
    sha256: 'a03779c86df3323075f5e796cb2ce5029f00ec8869eee3fdfb897afe36c6d002',
    sizeBytes: 147_964_211,
  },
  {
    id: 'small',
    latencyTier: 'ok',
    sha256: '1be3a9b2063867b937e64e2ec7483364a79917e157fa98c5d94b5c1fffea987b',
    sizeBytes: 487_601_967,
  },
  {
    id: 'small.en',
    latencyTier: 'ok',
    sha256: 'c6138d6d58ecc8322097e0f987c32f1be8bb0a18532a3f88f734d1bbf9c41e5d',
    sizeBytes: 487_614_201,
  },
  {
    id: 'medium',
    latencyTier: 'slow',
    sha256: '6c14d5adee5f86394037b4e4e8b59f1673b6cee10e3cf0b11bbdbee79c156208',
    sizeBytes: 1_533_763_059,
  },
  {
    id: 'medium.en',
    latencyTier: 'slow',
    sha256: 'cc37e93478338ec7700281a7ac30a10128929eb8f427dda2e865faa8f6da4356',
    sizeBytes: 1_533_774_781,
  },
  {
    id: 'large-v3-turbo',
    latencyTier: 'slow',
    sha256: '1fc70f774d38eb169993ac391eea357ef47c88757ef72ee5943879b7e8e2bc69',
    sizeBytes: 1_624_555_275,
  },
  {
    id: 'large-v3',
    latencyTier: 'slow',
    sha256: '64d182b440b98d5203c4f9bd541544d84c605196c4f7b845dfa11fb23594d1e2',
    sizeBytes: 3_095_033_483,
  },
]);
