name: 'release-happ'
on:
  workflow_dispatch:

jobs:
  publish-happ:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    outputs:
      releaseId: ${{ steps.create-release.outputs.id }}
    steps:
      - uses: actions/checkout@v4

      - name: Download HC
        run: |
          node ./scripts/fetch-hc.mjs

      - name: Install rust wasm32-unknown-unknown
        run: |
          rustup target install wasm32-unknown-unknown

      - name: Build
        run: |
          RUSTFLAGS='--cfg getrandom_backend="'"custom"'"' cargo build --release --target-dir target --target wasm32-unknown-unknown --workspace

      - name: Install wasm-opt
        run: |
          BIN_VER=119
          curl -sL -o /tmp/binaryen.tar.gz \
            https://github.com/WebAssembly/binaryen/releases/download/version_${BIN_VER}/binaryen-version_${BIN_VER}-x86_64-linux.tar.gz
          tar -xzf /tmp/binaryen.tar.gz -C /tmp
          echo "/tmp/binaryen-version_${BIN_VER}/bin" >> $GITHUB_PATH

      - name: Optimize all wasms
        run: |
          node ./scripts/wasm-opt-all.mjs

      - name: Pack
        run: |
          ./resources/bins/hc app pack ./workdir --recursive

      - name: Retrieve version
        run: |
          echo "APP_VERSION=$(cat package.json | grep -oP '(?<="version": ")[^"]*')" >> $GITHUB_OUTPUT
          echo "HOLOCHAIN_VERSION=$(node ./scripts/read-holochain-version.mjs)" >> $GITHUB_OUTPUT
        id: version

      - id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: 'workdir/group.happ'
          body: 'See assets below to download and install this version.'
          name: Group happ v${{ steps.version.outputs.APP_VERSION }}-${{ steps.version.outputs.HOLOCHAIN_VERSION }}
          tag: group-happ-v${{ steps.version.outputs.APP_VERSION }}
          prerelease: true
          draft: true
